### ISSUE TITLE
Hanwha Vision QND-6021: IRMode is out of range

### ISSUE THREAD

**Issue by djarbz** [MilestoneSystemsInc/PowerShellSamples#156]
I'm trying to update some camera stream settings and I am getting the following error:
```
WARNING: [12:02:02][Update-Stream] Failed to apply stream update [2) SUPER HIGH]:
[C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\24.1.6\MilestonePSTools.psm1:HandleValidateResultException:6961]:
ErrorOutOfRange: Invalid value for property "device:0.0/IRMode/ceef0a27-dc8c-4215-a4d0-c933db425e0b" on Settings.
ErrorText = "IRMode is out of range".
Origin = Set-VmsCameraStream | Exception of type 'VideoOS.Platform.Proxy.ConfigApi.ValidateResultException' was thrown.

at HandleValidateResultException<Process>, C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\24.1.6\MilestonePSTools.psm1: line 2273
at Set-VmsCameraStream<End>, C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\24.1.6\MilestonePSTools.psm1: line 6961
at Update-Stream, C:\Video Server Assets\Scripts\Set-CameraConfigV2.ps1: line 635
at <ScriptBlock>, C:\Video Server Assets\Scripts\Set-CameraConfigV2.ps1: line 680
at Update-Device, C:\Video Server Assets\Scripts\Set-CameraConfigV2.ps1: line 652
at <ScriptBlock>, C:\Video Server Assets\Scripts\Set-CameraConfigV2.ps1: line 721
```

Here is what I am passing to `set-VmsCameraStream`.
```
Set-VmsCameraStream -Stream $Stream @streamConfig -Confirm:$false -ErrorAction Stop
```
@StreamConfig
```
LiveMode: WhenNeeded
DisplayName: 2) SUPER HIGH
Settings:
  ControlMode: VBR
  Resolution: 1280x720
  Codec: h265
  Framerate: 15
  StreamingMode: RTP_RTSP_TCP
```
